### ISSUE TITLE
Q 143 Wrong answer

### ISSUE THREAD

**Issue by Tejaxx7** [Ditectrev/Microsoft-Azure-AZ-204-Developing-Solutions-for-Microsoft-Azure-Practice-Tests-Exams-Question-Answer#10]
https://learn.microsoft.com/en-us/azure/service-bus-messaging/service-bus-azure-and-service-bus-queues-compared-contrasted

find the above link which gives a comparison between azure storage queue vs azure service bus

it clearly mentioned to use **_service bus_**  if transactions and guaranteed FIFO behaviour is needed.

**Comment by danieldanielecki** [comment]
Correct! Fixed in https://github.com/Ditectrev/Microsoft-Azure-AZ-204-Developing-Solutions-for-Microsoft-Azure-Practice-Tests-Exams-Question-Answer/commit/cd2b500c904e4504524785d217d8c96684f17de7.
