### ISSUE TITLE
Q 181 wrong answer

### ISSUE THREAD

**Issue by Tejaxx7** [Ditectrev/Microsoft-Azure-AZ-204-Developing-Solutions-for-Microsoft-Azure-Practice-Tests-Exams-Question-Answer#11]
:white_check_mark: Run the az keyvault update --enable-soft-delete true --enable-purge-protection true CLI.
 :x: Run the az keyvault update --enable-soft-delete false CLI.

**Comment by danieldanielecki** [comment]
Correct, thanks! Fixed in https://github.com/Ditectrev/Microsoft-Azure-AZ-204-Developing-Solutions-for-Microsoft-Azure-Practice-Tests-Exams-Question-Answer/commit/6c65868af4e34c4282d36037a1237625c9b0b0d5.
