### ISSUE TITLE
Q 205 wrong answer

### ISSUE THREAD

**Issue by Tejaxx7** [Ditectrev/Microsoft-Azure-AZ-204-Developing-Solutions-for-Microsoft-Azure-Practice-Tests-Exams-Question-Answer#12]
$partitionKeyPath = '/EmployeeId'
 query 2: SELECT * FROM c WHERE c.UserID = '12345'
 
 Q: The second query statement is a cross-partition query.
given answer: yes.
correct answer: no.

since partition happens on employee id basis(1xxxx on one partition, 2xxxx on 2nd partition). cosmos db knows in which exact partition employee id 12345 is present.  so it will be a in-partition query. 

this is my justification. please checka and update.

**Comment by danieldanielecki** [comment]
Please refer to https://www.examtopics.com/discussions/microsoft/view/56335-exam-az-204-topic-4-question-34-discussion/ discussion, there's more than enough about this topic :)

**Comment by Tejaxx7** [comment]
sorry second statemnt has query with userId but not employeeId. 
I overlooked.

**Comment by danieldanielecki** [comment]
> sorry second statemnt has query with userId but not employeeId. I overlooked.

no worries, we're all learning :)
