### ISSUE TITLE
Correctness of the answers

### ISSUE THREAD

**Issue by xmasctf** [Ditectrev/Microsoft-Azure-AZ-204-Developing-Solutions-for-Microsoft-Azure-Practice-Tests-Exams-Question-Answer#4]
Hi,

I came across your Practice exam questions. Since you're selling those courses and questions in PDF form, I'm wondering, how sure you are, that the answers are correct. I'm reading through the questions and I don't agree with all the answers. Can you take a look at that, and tell me what you think?

Here are a few examples:

[Question 18](https://github.com/Ditectrev/Microsoft-Azure-AZ-204-Developing-Solutions-for-Microsoft-Azure-Practice-Tests-Exams-Question-Answer#you-develop-an-http-triggered-azure-function-app-to-process-azure-storage-blob-data-the-app-is-triggered-using-an-output-binding-on-the-blob-the-app-continues-to-time-out-after-four-minutes-the-app-must-process-the-blob-data-you-need-to-ensure-the-app-does-not-time-out-and-processes-the-blob-data-solution-configure-the-app-to-use-an-app-service-hosting-plan-and-enable-the-always-on-setting-does-the-solution-meet-the-goal).
Your answer is YES, but according to [https://learn.microsoft.com/en-us/azure/storage/blobs/storage-blob-event-overview](https://learn.microsoft.com/en-us/azure/storage/blobs/storage-blob-event-overview) There is no service level agreement around the time it takes for a message to arrive. It's not uncommon for messages to arrive anywhere from 30 minutes to two hours. Should the answer be NO instead, since the process to produce a mobile-friendly version of the image must start in less than one minute?

[Question 79](https://github.com/Ditectrev/Microsoft-Azure-AZ-204-Developing-Solutions-for-Microsoft-Azure-Practice-Tests-Exams-Question-Answer#you-provide-an-azure-api-management-managed-web-service-to-clients-the-back-end-web-service-implements-http-strict-transport-security-hsts-every-request-to-the-backend-service-must-include-a-valid-http-authorization-header-you-need-to-configure-the-azure-api-management-instance-with-an-authentication-policy-which-two-policies-can-you-use).
Your answer is _Certificate Authentication_ and _OAuth Client Credential Grant_. Shouldn't be _Basic Authentication_ one of the answers as service must include a valid HTTP authorization header?

[Question 81](https://github.com/Ditectrev/Microsoft-Azure-AZ-204-Developing-Solutions-for-Microsoft-Azure-Practice-Tests-Exams-Question-Answer#you-are-developing-an-aspnet-core-app-that-includes-feature-flags-which-are-managed-by-azure-app-configuration-you-create-an-azure-app-configuration-store-named-appfeatureflagstore-that-contains-a-feature-flag-named-export-you-need-to-update-the-app-to-meet-the-following-requirements-use-the-export-feature-in-the-app-without-requiring-a-restart-of-the-app-validate-users-before-users-are-allowed-access-to-secure-resources-permit-users-to-access-secure-resources-how-should-you-complete-the-code-segment)
You are saying that the last answer should be _app.UseStaticFiles();_, but according to the documentation UseAzureAppConfiguration middleware is the one that allows the configuration settings registered for refresh to be updated while the ASP.NET Core web app continues to receive requests.

[Question 101](https://github.com/Ditectrev/Microsoft-Azure-AZ-204-Developing-Solutions-for-Microsoft-Azure-Practice-Tests-Exams-Question-Answer#you-plan-to-deploy-a-web-app-to-app-service-on-linux-you-create-an-app-service-plan-you-create-and-push-a-custom-docker-image-that-contains-the-web-app-to-azure-container-registry-you-need-to-access-the-console-logs-generated-from-inside-the-container-in-real-time-how-should-you-complete-the-azure-cli-command)
Your answer in the last input field is that we should use _az webapp log download_, but since we want to access the console logs in real-time, shouldn't we use _az webapp log tail_ option? Even Microsoft documentation says that _"The download command may not work with web apps running on Linux."_.

And as I said, those are only 4 examples, there are many more. Did you verify your answers, and can you confirm that they are 100% correct?

Kind regards.

**Comment by danieldanielecki** [comment]
@xmasctf, thanks a lot for raising your concern.

I re-checked these questions, and the answers needed to be corrected. Thank you so much for your contribution; the fix is incorporated in https://github.com/Ditectrev/Microsoft-Azure-AZ-204-Developing-Solutions-for-Microsoft-Azure-Practice-Tests-Exams-Question-Answer/commit/3dd92d48c3f62367da1e7489e19bdfb8aecc20a5 and will be included in the next release

Lastly, I can't guarantee I'm 100% correct, but I am convinced you can pass the exam easily with what is currently available. However, with Students contribution we're constantly improving them.
