### ISSUE TITLE
Question 1 duplicated answer

### ISSUE THREAD

**Issue by ricardojcs** [Ditectrev/Microsoft-Azure-AZ-204-Developing-Solutions-for-Microsoft-Azure-Practice-Tests-Exams-Question-Answer#5]
In the first Question Option "**- [ ] Number of VM instances: 4. Pricing tier: Isolated.**" is duplicated.

**Comment by danieldanielecki** [comment]
@ricardojcs, thanks!
Deleted in https://github.com/Ditectrev/Microsoft-Azure-AZ-204-Developing-Solutions-for-Microsoft-Azure-Practice-Tests-Exams-Question-Answer/commit/fb3a53330276730249da95bef5f86bfe5a840e3f
