### ISSUE TITLE
Q 141 answer is deprecated.

### ISSUE THREAD

**Issue by Tejaxx7** [Ditectrev/Microsoft-Azure-AZ-204-Developing-Solutions-for-Microsoft-Azure-Practice-Tests-Exams-Question-Answer#9]
https://learn.microsoft.com/en-us/previous-versions/azure/azure-monitor/app/availability-multistep

this above link says use **Custom Track Availability Test** instead of the **deprecated multi-step web test.** 

the answer needs to be updated.

**Comment by danieldanielecki** [comment]
Thanks, the answer required an improvement, but it's answer B, because URL ping test is enough.

Fixed in https://github.com/Ditectrev/Microsoft-Azure-AZ-204-Developing-Solutions-for-Microsoft-Azure-Practice-Tests-Exams-Question-Answer/commit/e5dd309a8a31c27acf0de20cd1c26274e5a5cd21.
